### ISSUE TITLE
Don't change 'statusline' / 'cursorline'

### ISSUE THREAD

**Issue by Pyrohh** [fmoralesc/vim-tutor-mode#15]
It's intrusive IMO, and I don't see its purpose currently as `tutor#InfoText` looks unused.

Regarding cursorline, do we really need it? I might be missing something there.

**Comment by fmoralesc** [comment]
'cursorline' was enabled because it made sense to me to have it enabled for the most basic tutorial, but I see how that might be unwanted. I think a way to allow the tutorial files to change buffer local settings should be good to have, to allow custom behaviors in different tutorials.

As for `statusline`, that can be justified the same way. We could remove it for now, but we might want to re-add it later (to show, for example, a percentage of how much of the tutorial the user has worked on, or something like that). I find using the user/default statusline doesn't make much sense for special files like `.tutor` documents, which are displayed as scratch buffers.

**Comment by Pyrohh** [comment]
> I think a way to allow the tutorial files to change buffer local settings should be good to have, to allow custom behaviors in different tutorials.

Why not just a modeline?

> As for statusline, that can be justified the same way. We could remove it for now, but we might want to re-add it later (to show, for example, a percentage of how much of the tutorial the user has worked on, or something like that). 

I see what you mean regarding the percentage, but I'm still on the fence of modifying the user's status line, especially when a percentage already shows in the right hand corner (percentage through the file, I guess you're referring to percentage of tasks completed).

**Comment by fmoralesc** [comment]
Ah, sneaky move! (that PR)

> Why not just a modeline?

Yes, might be enough.

> I see what you mean regarding the percentage, but I'm still on the fence of modifying the user's status line, especially when a percentage already shows in the right hand corner (percentage through the file, I guess you're referring to percentage of tasks completed).

But the statusline is buffer local, so we are not overriding the user configuration (in my view). And yes, I'm talking about task completed or tasks + sections "read".

**Comment by Pyrohh** [comment]
> But the statusline is buffer local, so we are not overriding the user configuration (in my view). And yes, I'm talking about task completed or tasks + sections "read".

Ah, didn't know that. Yes perhaps 

> Ah, sneaky move! (that PR)

You said we can remove it for now, so I though that was a yes :grin:

**Comment by fmoralesc** [comment]
I think removing the cursorline setting is OK. 

Not sure yet about the statusline. Either, I would keep the `tutor#InfoText()` function, if only not having to write it again later.
